### ISSUE TITLE
[EDMTP-438] Fix Option Provider docs

### ISSUE THREAD

**Issue by smiakchilo** [exadel-inc/etoolbox-authoring-kit#223]
See the following code snippet from [Option Provider](https://github.com/exadel-inc/etoolbox-authoring-kit/blob/master/docs/md/option-provider.md) manual
![image](https://user-images.githubusercontent.com/48795460/136030563-e39c0c7b-c9a2-4915-a54e-92d20b64b5e3.png)

Expected result: Instead of `"update-options"`, the following string literal is used: `DependsOnActions.UPDATE_OPTIONS`

**Comment by Simba-97** [comment]
Hello @smiakchilo can I make a PR for this issue?

**Comment by smiakchilo** [comment]
You are welcome)
