### ISSUE TITLE
[EAK-238] Add the ability to create a complex multifield even when there's a single nested element

### ISSUE THREAD

**Issue by smiakchilo** [exadel-inc/etoolbox-authoring-kit#238]
In AEM, Multifields exist in two flavors: "simple" (data is stored as an array-typed property) and "complex" (data is stored in nested JCR nodes). Most of the time, simple multifield buildup is used when there is only nested field, and complex multifield is used when there are more.
_Currently_, `@Multifield` annotation does not support choosing on the flavor, and the multifield handler automatically renders simple multifields when it sees a single nested field.
_Expected result_: user has the abuility to instruct the plugin to create a simple or a complex multifield, or leave it by default (falls back to the current behavior).
_Suggestions on implementation_: Method `@interface Multifield {boolean complex() default false;}` would probably do,

**Comment by Alexey-Chernyakov** [comment]
#243
