### ISSUE TITLE
[EAK-359] Add the ability to define overridable placeholders for dialog properties

### ISSUE THREAD

**Issue by liubou-masiuk** [exadel-inc/etoolbox-authoring-kit#359]
**As a** toolkit user
**I want** to have the ability to define placeholders for dialog properties (such as fieldLabel, fieldDescription, but other widget-specific properties may be required).
**So that** I can define flexible 'building blocks' for the dialog that may change depending on the context.

❕ user should be able to define the default value for the property
❕ user should be able to override property value anywhere the field is used (in `@FieldSet`, `@Multifield`, where else?)
❕ need to think about template syntax, it should be easily distinguishable from Granite UI's [expression language](https://helpx.adobe.com/experience-manager/6-5/sites/developing/using/reference-materials/granite-ui/api/jcr_root/libs/granite/ui/docs/server/el.html)

**Comment by smiakchilo** [comment]
Implemented in 2.4.0
