### ISSUE TITLE
[EAK-370] DependsOn annotation does not support arrays in query

### ISSUE THREAD

**Issue by yminkevich** [exadel-inc/etoolbox-authoring-kit#370]
Expression:
` @DependsOn(query = "['a', 'b', 'c', 'd', 'e'].includes(@type(coral-multifield-item))")`
Current result:
<img width="616" alt="Capture" src="https://user-images.githubusercontent.com/62335478/179995006-05dfa833-54b1-4ac2-97b9-8db4f834bbbb.PNG">
Expected result: 
arrays should be stored and resolved correctly without additional effort with escaping brackets

**Comment by mhoroshko** [comment]
currently it can be it fixed with `@DependsOn(query = "\\['a', 'b', 'c', 'd', 'e'\\].includes(@type(coral-multifield-item))")`

**Comment by smiakchilo** [comment]
Scheduled to release in version 2.2.2
