### ISSUE TITLE
[EAK-414] Disallow standalone usage of nested toolkit annotations

### ISSUE THREAD

**Issue by liubou-masiuk** [exadel-inc/etoolbox-authoring-kit#414]
Scope: 

1. Identify toolkit annotations that are used **only** inside other annotations (e.g. `@OptionProvider` can only be used inside `@Select`, `@RadioGroup` and `@Autocomplete`). 
2. Disallow using such annotations directly (e.g. adding them onto fields, methods, etc.) by specifying enpty target (`@Target({})`) for these annotations

**Comment by smiakchilo** [comment]
Implemented in v. 2.3.0
