### ISSUE TITLE
[EAK-427] `@Place(before = ...)` causes unexpected field order changes

### ISSUE THREAD

**Issue by liubou-masiuk** [exadel-inc/etoolbox-authoring-kit#427]
**Preconditions:** Toolkit user wants to adjuct fields order and move a field higher using `@Place(before = ...)`

```
@AemComponent(path="content/testDialog", writeMode = WriteMode.CREATE, title = "Dialog")
@Dialog
public class TestDialog {
    @DialogField
    @TextField
    private String a;

    @DialogField
    @TextField
    private String b;

    @DialogField
    @TextField
    private String c;

    @DialogField
    @TextField
    @Place(before = @ClassMember("a"))
    private String first;

}

```
**Expected result:** Fields order: `first`, `a`, `b`, `с`. "natural" field order is preserved, only the field with `@Place(before = ...)` is moved relatively to other fields. 
**Actual result:** Fields order: `b`, `c`, `first`, `a`. field `a` is shifted so that field `first` is in the right position relatively to this field.

**Notes:** strangely enough, `@Place(after= ...)` works as expected in this case

**Comment by smiakchilo** [comment]
Implemented in https://github.com/exadel-inc/etoolbox-authoring-kit/pull/482; release in v. 2.4.1
