### ISSUE TITLE
[EAK-502] Add the ability to reuse AllowedChildren policies

### ISSUE THREAD

**Issue by liubou-masiuk** [exadel-inc/etoolbox-authoring-kit#502]
Sometimes there is a fixed set of policies that may be used in multiple components. One such example is header/footer policies that can be reused across multiple pages. Currently, the user can either specify the allowed children list on the current component, or via a separate "View" class. However, there is no ability to combine the 2 approaches and reusable policies via "Views" while having some custom policies for the current component. Also, there is no ability to add multiple views that handle AllowedChildren

In the bounds of this ticket, we should either add an ability to combine AllowedChildren from views and the current component or come up with another way to have reusable policies.

**Comment by smiakchilo** [comment]
Implemented in v. 2.5.2
