### ISSUE TITLE
[EAK-503] Add validation for `@DropTarget`'s nodeName property

### ISSUE THREAD

**Issue by liubou-masiuk** [exadel-inc/etoolbox-authoring-kit#503]
Currently, there is a possibility of getting an NPE if the user specifies an empty string in  `@DropTarget`'s nodeName property:
```
@ChildEditConfig(dropTargets = @DropTargetConfig(nodeName = "", propertyName = "property"))
```

Need to add validation for this property

**Comment by smiakchilo** [comment]
Scheduled for release in v.2.5.1
